let pizzaJson = [
    {id:1, name:'Mussarela',
         img:'images/pizza.png',
         price:20.19, sizes:['100g', '530g', '860g'],
         description:'Molho de tomate, Queijo Mussarela, Creme de Cheddar, Cebola, Orégano'},
    {id:2,name:'Calabresa',
        img:'images/pizza2.png',
        price:20.00, sizes:['320g','530g', '860g'], 
        description:'Molho Artesanal de Tomate, Mussarela, Calabresa, Orégano'},
    {id:3, name:'Quatro Queijos',
        img:'images/pizza3.png',
        price:17.45, sizes:['320g', '530g', '860g'],
        description:'Molho de tomate, Queijo mussarela, Queijo gorgonzola, Queijo parmesão, Queijo provolone'},
    {id:4, name:'Americana',
        img:'images/pizza4.png', 
        price:19.77, sizes:['320g', '530g', '860g'],
        description:'Molho de tomate, Queijo mussarela, Bacon, Milho, Ovo, Batata palha'},
    {id:5, name:'Frango', 
        img:'images/pizza5.png', 
        price:21.43, 
        sizes:['320g', '530g', '860g'], 
        description:'molho de tomate, Queijo mussarela, Frango desfiado, milho, com ou sem Catupiry'},
    {id:6, name:'Moda da Casa', 
        img:'images/pizza6.png', 
        price:18.55, sizes:['320g', '530g', '860g'], 
        description:'Molho de tomate, Queijo Mussarela, Presunto, Bacon, Cebola, Pimentão, Azeitonas'},
    {id:7, name:'Chocolate', 
        img:'images/pizza7.png', 
        price:22.36, sizes:['320g', '530g', '860g'], 
        description:'Chocolate derretido, Opções: morangos, banana, granulado, ou castanhas para decorar'}
];